04_TagHelpers/Models/Employe.cs
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace TagHelpers.Models
{
    public class Employe
    {
        public int Id { get; set; }

        [DisplayName("Nom")]
        public string Name { get; set; } = string.Empty;

        [DisplayName("Salaire")]
        public double Salary { get; set; }

        [DisplayName("Actif")]
        public bool IsActif { get; set; } = true;

        public string Email { get; set; } = string.Empty;

        public int DepartementId { get; set; }

        public DateTime DateEntree { get; set;}

        public EmployeType Type { get; set; } = EmployeType.DEBUTANT;
    }

    public enum EmployeType
    {
        DEBUTANT,
        JUNIOR,
        SENIOR
    }
}

04_TagHelpers/Models/ErrorViewModel.cs
namespace TagHelpers.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04_TagHelpers/Controllers/EmployeController.cs
using Microsoft.AspNetCore.Mvc;
using TagHelpers.Models;

namespace TagHelpers.Controllers
{
    public class EmployeController : Controller
    {
        private readonly ILogger<EmployeController> _logger;

        public EmployeController(ILogger<EmployeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Create(Employe emp)
        {
            //return View(emp);
            return View("CreateHtmlHelpers", emp);
        }

        public IActionResult Bonjour(Employe emp)
        {
            return View(emp);
        }
    }
}

04_TagHelpers/Views/Employe/Bonjour.cshtml
@using TagHelpers.Helpers;
@model Employe
@{
    ViewData["Title"] = "Create Employe";
}

<h2>Tag Helper</h2>

@*<div><a href="mailto:@Model.Email">@Model.Name</a> est de type @Model.Type gagne @Model.Salary</div>*@

<employe name=@Model.Name salary=@Model.Salary type=@Model.Type email=@Model.Email />

@Html.Employe(@Model.Name, @Model.Salary.ToString(), @Model.Type.ToString(), @Model.Email)

04_TagHelpers/Views/Employe/Create.cshtml
@model Employe
@{
    ViewData["Title"] = "Create Employe";
}

<h1>New Employe</h1>

<form method="post" asp-action="Bonjour">

   <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control"/>
   </div>
    <div class="mb-3">
        <label asp-for="Salary"></label>
        <input asp-for="Salary" class="form-control" value=""/>
    </div>

    <div class="mb-3">
        <label asp-for="IsActif"></label>
        <input asp-for="IsActif" class="form-check-input" />
    </div>

    <div class="mb-3">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="DepartementId"></label>
        <input asp-for="DepartementId" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="DateEntree"></label>
        <input asp-for="DateEntree" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Type"></label>
        <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<EmployeType>()">
            <option>Please select one</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

04_TagHelpers/Views/Employe/CreateHtmlHelpers.cshtml
@model Employe
@{
    ViewData["Title"] = "Create Employe avec HTML Helpers";
}

<h1>New Employe</h1>

@using (Html.BeginForm("Bonjour", "Employe", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="mb-3">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class="form-control"})
    </div>

    <div class="mb-3">
        @Html.LabelFor(model => model.Salary)
        @Html.TextBoxFor(model => model.Salary, new { @class="form-control"})
    </div>

    <div class="mb-3">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class="form-control"})
    </div>

    <div class="mb-3">
        @Html.LabelFor(model => model.IsActif)
        @Html.EditorFor(model => model.IsActif, new { htmlAttibutes = new { @class="form-check-input"}})
    </div>

    <div class="mb-3">
        @Html.LabelFor(model => model.Type)
        @Html.DropDownListFor(model => model.Type, Html.GetEnumSelectList<EmployeType>(), "Select type",  new { @class="form-control"})
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
}

04_TagHelpers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TagHelpers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TagHelpers.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>